[tool.poetry]
name = "dqn-demo"
version = "0.1.0"
description = ""
authors = ["Dimitar Gueorguiev"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12.4"
keras = { version = "==2.2.4" }


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
